### PR TITLE
Better cache, fixes #21

### LINKED ISSUE #21: Bad performance
On small machines, in my case a Raspberry Pi, this addon has a really bad performance caused by the frequent parsing of xml by BeautifulSoup. 
In my case it takes about 5 minutes to load the list of trailers. Every time we call __get_source it parses the xml again, every parse takes almost a minute to complete. 
Caching the the parsed trailers list gives much better performance as we only parse it one time.

### PR DESCRIPTION
**Pull request by foreverguest**
Cache parsed xml improving general performance
Remove file caching

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Don't wanna use this common cache

**Comment by MartijnKaijser** [comment]
or do you want this @dersphere ?

**Comment by dersphere** [comment]
I don't like the implementation of common cache, but if it improves the execution speed with no or less side effects...

You can choose. Fair to say that I didn't say "generally no" to #21

**Comment by foreverguest** [comment]
Do you have another suggestion to improve the performance? I was thinking in replacing BeautifulSoup with ElementTree to improve xml parsing performance. But if you have another idea, I'm willing to explore.

**Pull request closed without merging**
